language: ruby
rvm:
- 2.3.1
install:
- ./bin/setup
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: hejtmy
  - EMAIL: hejtmy@gmail.com
  - secure: op5jpu7VjQ7JlVZZxOK1DPQ85wKCwNYsrTqfWMHXv7xArsJ3CKNAZtADDjneOS6c3LkDcfmVYMGVPHySHcvk4troqzrFpCCni7A5OKGtHRsYsSAdq322MqHlPucx8Hzewk1o3QCqWcVlB1kZTQqSRGgbUEU/xEyoG62fLDZ2AskIDqjH6/OzkwIcgtzJELZ0IkUp+CPDCGf+1dnwTwkXKjbKwhIYkdq9DjBcD/uQp5k82cam8r/OVho14rrhQAgV2K2j5UJ1tQoBY4O1STqZ+4/eJ0giMfl1pX/LxFK15CCDuYUlLJdV3lXu2oEldTaiTfo3Y3ilp8ZlN9bbQGjsVsehz2hP90cU1gLqOtS5EAUTYPAYf0Q2/cxoa41F7S6+dWBL7Qns2L51P1+35Oxeq/xDHMNDW2j2OfN++zS1XpMGKjQl6np79Nkj68LSlnISZqIbquQjrLPDrrYGFeEM7PAk5LtoH4NbJP6XFefJahZj++s6Lilr5w8hJaARdNGzloVT3ZYJZRhFU/FdMIdhWCFnrEOTzQSDVWS20EVMvVYHoXMtHvn7zjTzhCYlcTnH5LDQUqSdJBF40eYfbslqghmHn+kYunhUxzWNZnicPM06FwFSwg8UGvmXNPT+wR1uDW7GnvcnqPAkQqwbJFDrIN/jMYBmu6cPKPLuTZeNjX4=
