# Site settings
title: Lab code
email:  hejtmy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: http:\\github.com\lab-code\
  - title: slack
    url: http:\\lab-code.slack.com\

    # Members information. Shown on About page.
members:
  - name: Lukáš Hejtmánek
    position: CEO of my life
    text: Founder
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:hejtmy@gmail.com
      - title: twitter
        url: http:\\twitter.com\hejtmy_
